using Indamin.Performance.Data;
using Indamin.Performance.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace Indamin.Performance.Controllers;
[Authorize(Policy="AdminOnly")] public class AdminController(AppDbContext db,ExcelService excel):Controller{
 public async Task<IActionResult> Periods()=>View(await db.Periods.OrderByDescending(x=>x.StartAt).ToListAsync());
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult>CreatePeriod(string title,string startJalali,string endJalali,string? description){if(string.IsNullOrWhiteSpace(title))return BadRequest();var s=PerformanceService.Jalali(startJalali);var e=PerformanceService.Jalali(endJalali).AddDays(1).AddTicks(-1);if(e<s)return BadRequest("بازه زمانی نامعتبر است.");if(await db.Periods.AnyAsync(x=>x.IsOpen&&s<=x.EndAt&&e>=x.StartAt))return BadRequest("بازه با یک دوره فعال دیگر هم‌پوشانی دارد.");db.Periods.Add(new EvaluationPeriod{Title=title,StartJalali=startJalali,EndJalali=endJalali,StartAt=s,EndAt=e,Description=description,IsOpen=true});await db.SaveChangesAsync();return RedirectToAction(nameof(Periods));}
 public async Task<IActionResult> Employees(string? q){var x=db.Employees.Include(e=>e.Position).Include(e=>e.Unit).AsQueryable();if(!string.IsNullOrWhiteSpace(q))x=x.Where(e=>e.FullName.Contains(q)||e.PersonnelNo.Contains(q));return View(await x.OrderBy(e=>e.FullName).ToListAsync());}
 [HttpGet]public IActionResult ImportEmployees()=>View();
 [HttpPost][ValidateAntiForgeryToken]public async Task<IActionResult>ImportEmployees(IFormFile file){if(file==null||file.Length==0)return BadRequest("فایل اکسل انتخاب نشده است.");var rows=excel.ReadEmployees(file.OpenReadStream());var positions=await db.Positions.ToListAsync();var units=await db.OrgUnits.ToListAsync();int ok=0;foreach(var r in rows){var pos=positions.FirstOrDefault(x=>x.Code==r.PositionCode);var unit=units.FirstOrDefault(x=>x.Code==r.UnitCode);if(pos==null||unit==null)continue;var e=await db.Employees.SingleOrDefaultAsync(x=>x.PersonnelNo==r.PersonnelNo);var eval=r.Evaluator is "بله" or "1" or "yes";if(e==null)db.Employees.Add(new Employee{PersonnelNo=r.PersonnelNo,NationalNo=r.NationalNo,FullName=r.FullName,PositionId=pos.Id,UnitId=unit.Id,IsEvaluator=eval});else{e.NationalNo=r.NationalNo;e.FullName=r.FullName;e.PositionId=pos.Id;e.UnitId=unit.Id;e.IsEvaluator=eval;}ok++;}await db.SaveChangesAsync();var all=await db.Employees.ToListAsync();foreach(var r in rows){var e=all.FirstOrDefault(x=>x.PersonnelNo==r.PersonnelNo);if(e!=null)e.SupervisorId=all.FirstOrDefault(x=>x.PersonnelNo==r.SupervisorPersonnelNo)?.Id;}foreach(var e in all.Where(x=>x.IsEvaluator)){var u=await db.Users.SingleOrDefaultAsync(x=>x.UserName==e.PersonnelNo);if(u==null)db.Users.Add(new AppUser{UserName=e.PersonnelNo,DisplayName=e.FullName,EmployeeId=e.Id,PasswordHash=PasswordHasher.Hash("ChangeMe123!"),IsActive=true});else{u.EmployeeId=e.Id;u.DisplayName=e.FullName;u.IsActive=true;}}await db.SaveChangesAsync();TempData["Result"]=$"{ok} رکورد با موفقیت پردازش شد.";return RedirectToAction(nameof(Employees));}
 [HttpGet]public async Task<IActionResult>ExportEmployees(){var rows=await db.Employees.Include(x=>x.Position).Include(x=>x.Unit).ToListAsync();return File(excel.Employees(rows),"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Employees.xlsx");}
}