using System.Security.Claims;
using Indamin.Performance.Data;
using Indamin.Performance.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace Indamin.Performance.Controllers;
[Authorize] public class EvaluationController(AppDbContext db,PerformanceService ps):Controller{
 public async Task<IActionResult> Index(){var eid=int.Parse(User.FindFirstValue("EmployeeId")!);var p=await ps.CurrentPeriod();if(p==null)return View(new List<Row>());var ids=(await ps.GetDescendants(eid)).Select(x=>x.Id).ToList();var rows=await db.Employees.Include(x=>x.Position).Include(x=>x.Unit).Where(x=>ids.Contains(x.Id)).Select(x=>new Row(x.Id,x.FullName,x.PersonnelNo,x.Position!.Title,x.Unit!.Title)).ToListAsync();return View(rows);}
 public record Row(int Id,string Name,string PersonnelNo,string Position,string Unit);
 [HttpGet] public async Task<IActionResult> Form(int id){var evaluator=int.Parse(User.FindFirstValue("EmployeeId")!);if(!await ps.CanEvaluate(evaluator,id))return Forbid();var p=await ps.CurrentPeriod();if(p==null)return NotFound();var employee=await db.Employees.Include(x=>x.Position).FirstAsync(x=>x.Id==id);var qs=await db.Questions.Where(x=>x.PositionId==employee.PositionId&&x.IsActive).OrderBy(x=>x.SortOrder).ToListAsync();var ev=await db.Evaluations.Include(x=>x.Scores).SingleOrDefaultAsync(x=>x.PeriodId==p.Id&&x.EmployeeId==id);return View(new FormVm(p,employee,qs,ev));}
 [HttpPost][ValidateAntiForgeryToken] public async Task<IActionResult> Form(FormPost m){var evaluator=int.Parse(User.FindFirstValue("EmployeeId")!);if(!await ps.CanEvaluate(evaluator,m.EmployeeId))return Forbid();var p=await ps.CurrentPeriod();if(p==null)return NotFound();var editable=await ps.CanEdit(p);var ev=await db.Evaluations.Include(x=>x.Scores).SingleOrDefaultAsync(x=>x.PeriodId==p.Id&&x.EmployeeId==m.EmployeeId);if(ev==null){ev=new Evaluation{PeriodId=p.Id,EmployeeId=m.EmployeeId,EvaluatorId=evaluator};db.Evaluations.Add(ev);await db.SaveChangesAsync();}else if(ev.EvaluatorId!=evaluator){if(!editable)return BadRequest("خارج از بازه ارزیابی");}
 var qs=await db.Questions.Where(x=>x.PositionId==m.PositionId&&x.IsActive).ToListAsync();foreach(var q in qs){var score=m.Scores.TryGetValue(q.Id,out var s)?s:0;if(score<0||score>q.MaxScore)continue;var old=ev.Scores.FirstOrDefault(x=>x.QuestionId==q.Id);if(old==null)ev.Scores.Add(new EvaluationScore{QuestionId=q.Id,Score=score,Comment=m.Comments.TryGetValue(q.Id,out var c)?c:null});else if(old.Score!=score){db.ScoreHistory.Add(new EvaluationScoreHistory{EvaluationId=ev.Id,QuestionId=q.Id,OldScore=old.Score,NewScore=score,ChangedBy=evaluator,Reason=ev.EvaluatorId==evaluator?"اصلاح ارزیابی":"بازنگری ارزیاب بالادست"});old.Score=score;old.Comment=m.Comments.TryGetValue(q.Id,out var c)?c:null;old.UpdatedAt=DateTime.UtcNow;}}
 if(ev.EvaluatorId!=evaluator){db.ScoreHistory.Add(new EvaluationScoreHistory{EvaluationId=ev.Id,QuestionId=0,OldScore=0,NewScore=0,ChangedBy=evaluator,Reason="بازنگری ارزیاب بالادست"});ev.EvaluatorId=evaluator;}ev.Status=EvaluationStatus.Submitted;ev.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();return RedirectToAction(nameof(Index));}
 public record FormVm(EvaluationPeriod Period,Employee Employee,List<Question> Questions,Evaluation? Evaluation);
 public class FormPost{public int EmployeeId{get;set;}public int PositionId{get;set;}public Dictionary<int,decimal> Scores{get;set;}=[];public Dictionary<int,string> Comments{get;set;}=[];}
}