using System.Security.Claims;
using Indamin.Performance.Data;
using Indamin.Performance.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
namespace Indamin.Performance.Controllers;
[Authorize] public class EvaluationController(AppDbContext db,PerformanceService ps):Controller{
 public async Task<IActionResult> Index(){var eid=int.Parse(User.FindFirstValue("EmployeeId")!);var p=await ps.CurrentPeriod();if(p==null)return View(new List<Row>());var ids=(await ps.GetDirectSubordinates(eid)).Select(x=>x.Id).ToList();var rows=await db.Employees.Include(x=>x.Position).Include(x=>x.Unit).Where(x=>ids.Contains(x.Id)).Select(x=>new Row(x.Id,x.FullName,x.PersonnelNo,x.Position!.Title,x.Unit!.Title)).ToListAsync();return View(rows);}
 public record Row(int Id,string Name,string PersonnelNo,string Position,string Unit);
 [HttpGet] public async Task<IActionResult> Form(int id){var actor=int.Parse(User.FindFirstValue("EmployeeId")!);var p=await ps.CurrentPeriod();if(p==null)return NotFound();var employee=await db.Employees.Include(x=>x.Position).FirstOrDefaultAsync(x=>x.Id==id);if(employee==null)return NotFound();var ev=await db.Evaluations.Include(x=>x.Scores).SingleOrDefaultAsync(x=>x.PeriodId==p.Id&&x.EmployeeId==id);var allowed=await ps.CanEvaluate(actor,id)||(ev!=null&&await ps.CanReviewEvaluation(actor,ev));if(!allowed)return Forbid();var qs=await db.Questions.Where(x=>x.PositionId==employee.PositionId&&x.IsActive).OrderBy(x=>x.SortOrder).ToListAsync();return View(new FormVm(p,employee,qs,ev));}
 [HttpPost][ValidateAntiForgeryToken] public async Task<IActionResult> Form(FormPost m){var actor=int.Parse(User.FindFirstValue("EmployeeId")!);var p=await ps.CurrentPeriod();if(p==null)return NotFound();if(!await ps.CanEdit(p))return BadRequest("بازه ارزیابی پایان یافته است.");var ev=await db.Evaluations.Include(x=>x.Scores).SingleOrDefaultAsync(x=>x.PeriodId==p.Id&&x.EmployeeId==m.EmployeeId);if(ev==null){if(!await ps.CanEvaluate(actor,m.EmployeeId))return Forbid();ev=new Evaluation{PeriodId=p.Id,EmployeeId=m.EmployeeId,EvaluatorId=actor,OriginalEvaluatorId=actor};db.Evaluations.Add(ev);await db.SaveChangesAsync();}else if(!await ps.CanReviewEvaluation(actor,ev))return Forbid();
 var qs=await db.Questions.Where(x=>x.PositionId==m.PositionId&&x.IsActive).ToListAsync();foreach(var q in qs){var score=m.Scores.TryGetValue(q.Id,out var s)?s:0;if(score<0||score>q.MaxScore)continue;var old=ev.Scores.FirstOrDefault(x=>x.QuestionId==q.Id);var comment=m.Comments.TryGetValue(q.Id,out var c)?c:null;if(old==null)ev.Scores.Add(new EvaluationScore{QuestionId=q.Id,Score=score,Comment=comment});else if(old.Score!=score||old.Comment!=comment){db.ScoreHistory.Add(new EvaluationScoreHistory{EvaluationId=ev.Id,QuestionId=q.Id,OldScore=old.Score,NewScore=score,ChangedBy=actor,Reason=ev.EvaluatorId==actor?"اصلاح ارزیابی":"بازنگری ارزیاب بالادست"});old.Score=score;old.Comment=comment;old.UpdatedAt=DateTime.UtcNow;}}
 if(ev.EvaluatorId!=actor){db.EvaluatorHistory.Add(new EvaluatorChangeHistory{EvaluationId=ev.Id,PreviousEvaluatorId=ev.EvaluatorId,NewEvaluatorId=actor,ChangedBy=actor,Reason="بازنگری ارزیاب بالادست"});ev.EvaluatorId=actor;}ev.Status=EvaluationStatus.Submitted;ev.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();return RedirectToAction(nameof(Index));}
 public record FormVm(EvaluationPeriod Period,Employee Employee,List<Question> Questions,Evaluation? Evaluation);
 public class FormPost{public int EmployeeId{get;set;}public int PositionId{get;set;}public Dictionary<int,decimal> Scores{get;set;}=[];public Dictionary<int,string> Comments{get;set;}=[];}
}